
version: "2"
services:
  web:
    container_name: docker-node-mongo
    build: .
    ports:
    - "51005:51005"
    - "8181:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.crt:/etc/nginx/conf.d/localhost.crt;
      - ./localhost.key:/etc/nginx/conf.d/localhost.key;
    links:
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - datavolume-mongo:/var/lib/mongo
    ports:
      - "27017:27017"
  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD:password
      MYSQL_DATABASE:backend_demo
      MYSQL_USER:root
      MYSQL_PASSWORD:password
      MYSQL_ROOT_HOST=%
    image: mysql
    volumes:
      - datavolume-mysql:/var/lib/mysql
    ports:
       - "51006:3306"
volumes:
  datavolume-mysql:
  datavolume-mongo:  
  
      