
version: "2"
services:
  web:
    build: .
    ports:
    - "51005:51005"
    depends_on:
    - mongo
    - mysql
  mongo:
    image: mongo
    volumes:
      - my-datavolume:/var/lib/mongo
    ports:
      - "27017:27017"
  mysql:
      env_file:
        - mysql-server.env
      image: mysql
      volumes:
        - my-datavolume:/var/lib/mysql
      ports:
       - "3306:3306"
volumes:
  my-datavolume:
  
      