
version: "2"
services:
  web:
    container_name: docker-node-mongo
    build: .
    ports:
    - "51005:51005"
    - "80:80"
    - "443:443"
#    volumes:
#      - ./default:/etc/nginx/sites-available/default
#     - ./ssl/fullchain.pem:/etc/ssl/fullchain.pem
#      - ./ssl/privkey.pem:/etc/ssl/privkey.pem
    links:
      - mongo
      - mysqlhost
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - datavolume-mongo:/data/db
    ports:
      - "27017:27017"
  mysqlhost:
    container_name: mysqlhost
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backend_demo
    volumes:
      - datavolume-mysql:/var/lib/mysql
    ports:
       - "3306:3306"
volumes:
  datavolume-mysql:
  datavolume-mongo:  
  
      